# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawler.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcrawler.proto\x12\x07\x63rawler\"\t\n\x07Request\"\n\n\x08Response27\n\x07\x43rawler\x12,\n\x03Run\x12\x10.crawler.Request\x1a\x11.crawler.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crawler_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=26
  _REQUEST._serialized_end=35
  _RESPONSE._serialized_start=37
  _RESPONSE._serialized_end=47
  _CRAWLER._serialized_start=49
  _CRAWLER._serialized_end=104
# @@protoc_insertion_point(module_scope)
