# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: power_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10power_data.proto\x12\tpowerdata\"\x12\n\x10PowerDataRequest\"#\n\x11PowerDataResponse\x12\x0e\n\x06\x63svUrl\x18\x01 \x01(\t2c\n\x10PowerDataService\x12O\n\x10GetPowerDataInfo\x12\x1b.powerdata.PowerDataRequest\x1a\x1c.powerdata.PowerDataResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'power_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POWERDATAREQUEST._serialized_start=31
  _POWERDATAREQUEST._serialized_end=49
  _POWERDATARESPONSE._serialized_start=51
  _POWERDATARESPONSE._serialized_end=86
  _POWERDATASERVICE._serialized_start=88
  _POWERDATASERVICE._serialized_end=187
# @@protoc_insertion_point(module_scope)
