# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import power_data_pb2 as power__data__pb2


class PowerDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPowerDataInfo = channel.unary_unary(
                '/powerdata.PowerDataService/GetPowerDataInfo',
                request_serializer=power__data__pb2.PowerDataRequest.SerializeToString,
                response_deserializer=power__data__pb2.PowerDataResponse.FromString,
                )


class PowerDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPowerDataInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PowerDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPowerDataInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPowerDataInfo,
                    request_deserializer=power__data__pb2.PowerDataRequest.FromString,
                    response_serializer=power__data__pb2.PowerDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'powerdata.PowerDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PowerDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPowerDataInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/powerdata.PowerDataService/GetPowerDataInfo',
            power__data__pb2.PowerDataRequest.SerializeToString,
            power__data__pb2.PowerDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
