name: CD

on:
  push:
    tags:
      - v*.*.*-Testing.**
      - v*.*.*-Production.**

jobs:
  docker:
    runs-on: ubuntu-latest
    name: "Build Docker image and push to Harbor"
    steps:
      - name: Get version string
        id: get-version
        run: |
          tag=${{ github.event.push.tag_name }}
          echo "::set-output name=version::${tag:1}"
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: https://harbor.tsmc.n0b.me
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tsmc/controller:latest,tsmc/controller:${{ steps.get-version.outputs.version }}
          file: src/apps/controller/Dockerfile
