on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
        description: "The name of the image to build and push"
      dockerfile:
        type: string
        required: true
        description: "The path to the Dockerfile to build"
    secrets:
      HARBOR_USERNAME:
        required: true
      HARBOR_TOKEN:
        required: true

jobs:
  build-and-push-docker-image-to-harbor:
    runs-on: ubuntu-latest
    name: "Build Docker image and push to Harbor"
    if: contains(fromJSON('["push"]'), github.event_name) && contains(github.ref, format('refs/tags/{0}-', inputs.image_name))
    steps:
      - name: Set tag variable
        run: echo "TAG=$(basename ${{ github.ref }})" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: https://harbor.tsmc.n0b.me
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: harbor.tsmc.n0b.me/tsmc/${{ inputs.image_name }}:latest,harbor.tsmc.n0b.me/tsmc/${{ inputs.image_name }}:${{ env.TAG }}
          file: ${{ inputs.dockerfile }}
